spring:
  application:
    name: USERSERVICE
  datasource:
    username: postgres
    password: lol
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://structuremade.de:5431/structuremade
  jpa:
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: services
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://eureka.structuremade.de/eureka/
server:
  port: 80
